name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build , Test, and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main

      - name: Install Dependencies
        run: cd functions && npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.0.0
        with:
          # TODO - Update to use /scripts once deploy is implemented
          args: deploy --only functions -m $GITHUB_SHA
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
